<?php
namespace dapper\Render;

require_once __DIR__ . "/../../BaseCase.php";

/**
 * Test class for Route.
 * Generated by PHPUnit on 2011-12-13 at 08:29:38.
 */
class TextTest extends \BaseCase {
	
    function testInstantiateNoErrors()
    {
        new Text(array());
        // just a sanity test
        $this->assertTrue(true);
    }
    function testRenderView()
    {
        $php_template = new Text(array());
        ob_start();
        $php_template->render_view('users', array('test_message_var' => 'hello'));
        $rendered_view = ob_get_clean();
        $this->assertEquals(
            "View: users\narray (\n  'test_message_var' => 'hello',\n)",
            $rendered_view
        );
    }
    
}
