<?php
require_once __DIR__ . "/BaseTestCase.php";

/**
 * Test class for ExtractingClosure.
 * Generated by PHPUnit on 2011-12-13 at 08:27:29.
 */
class ExtractingClosureTest extends BaseTestCase {

    /**
     * @var ExtractingClosure
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ExtractingClosure;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement test__invoke().
     */
    public function test__invoke()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
