<?php
require_once __DIR__ . "/../BaseUnitTestCase.php";

/**
 * Test class for ExtractingClosure.
 * Generated by PHPUnit on 2011-12-13 at 08:27:29.
 */
class ExtractingClosureUnitTest extends BaseUnitTestCase {



    /**
     * @todo Implement test__invoke().
     */
    public function test__invoke()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
