<?php

require_once __DIR__ . "/../BaseUnitTestCase.php";

/**
 * Test class for Route.
 * Generated by PHPUnit on 2011-12-13 at 08:29:38.
 */
class RouteWorkUnitTest extends BaseUnitTestCase {
	

	/**
	 * @expectedException \InvalidArgumentException
	 */
	function testConstructorThrowsProperExceptionForInvalidHttpMethod()
	{
		$routeWork = new clear\Route(
			'/',
			'FU',
			'user',
			array()
		);
        $this->assertEquals('/',$routeWork->path());		
	}

    public function testRouteReturnsValueFromContructor()
    {
		$routeWork = new clear\Route('GET', '/user'	);
        $this->assertEquals('/user',$routeWork->path());
    }
	public function testRouteHasSlashedCorrected()
	{
		$routeWork = new clear\Route('GET', '/user/');
		$this->assertEquals('/user',$routeWork->path());
		
		$routeWork = new clear\Route('GET', 'user/');
		$this->assertEquals('/user',$routeWork->path());
		
		$routeWork = new clear\Route('GET', '');
		$this->assertEquals('/',$routeWork->path());
	}

    /**
     * @todo Implement testHttp_method().
     */
    public function testHttp_method()
    {
		$routeWork = new clear\Route('GET', '/user/');
		$this->assertEquals('/user',$routeWork->path());
    }

    /**
     * @todo Implement testController().
     */
    public function testController()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testUri_path_segments().
     */
    public function testUri_path_segments()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testExecutable_workload().
     */
    public function testExecutable_workload()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testTargeted_view().
     */
    public function testTargeted_view()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testExposed_work().
     */
    public function testExposed_work()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
