<?php

require_once __DIR__ . "/BaseTestCase.php";

/**
 * Test class for Util.
 * Generated by PHPUnit on 2011-12-13 at 08:30:23.
 */
class UtilTest extends BaseTestCase {

    /**
     * @var Util
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Util;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testArr_extract_key_pattern().
     */
    public function testArr_extract_key_pattern()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
