<?php
namespace dapper\Responder;
use dapper\Router;
use dapper\Route;
use dapper\Env;
use dapper\TemplateEngine\PhpTemplate;

require_once __DIR__ . "/../../BaseCase.php";

/**
 * Test class for Route.
 * Generated by PHPUnit on 2011-12-13 at 08:29:38.
 */
class HttpResponderTest extends \BaseCase {
    
    function testInstantiateNoErrors()
    {
        $this->markTestIncomplete("Need to re-implement the HttpResponder tests");
        new HttpResponder(
            new Router(
                new Route('get', '/')
            ),
            new PhpTemplate(array()),
            new Env(sys_get_temp_dir(), true)
        );
        // just a sanity test
        $this->assertTrue(true);
    }
    
    function testComplete()
    {
        $this->markTestIncomplete("Need to re-implement the HttpResponder tests");
        $responder = new HttpResponder(
            new Router(
                new Route('get', '/')
            ),
            new PhpTemplate(array()),
            new Env(sys_get_temp_dir(), true)
        );
        $responder->complete();
        // just sanity check
        $this->assertTrue(true);
    }

    
}
