<?php
namespace dapper\Responder;
use dapper\Router;
use dapper\Route;
use dapper\Env;
use dapper\Render\Text;

require_once __DIR__ . "/../../BaseCase.php";

/**
 * Test class for Route.
 * Generated by PHPUnit on 2011-12-13 at 08:29:38.
 */
class HttpResponderTest extends \BaseCase {
	
    function testInstantiateNoErrors()
    {
        new HttpResponder(
            new Router(
                new Route('get', '/')
            ),
            new Text(),
            new Env()
        );
        // just a sanity test
        $this->assertTrue(true);
    }
    
    function testComplete()
    {
        $responder = new HttpResponder(
            new Router(
                new Route('get', '/')
            ),
            new Text(),
            new Env()
        );
        $responder->complete();
        // just sanity check
        $this->assertTrue(true);
    }

    
}
