<?php
namespace clear\Responder;
use clear\Router;
use clear\Route;

require_once __DIR__ . "/../BaseCase.php";

/**
 * Test class for Route.
 * Generated by PHPUnit on 2011-12-13 at 08:29:38.
 */
class ResponderTest extends \BaseCase {
	
    function testInstantiateNoErrors()
    {
        new TestingResponse(
            array(),
            new Router(
                new Route('get', '/')
            )
        );
        // just a sanity test
        $this->assertTrue(true);
    }
    
    
    
    
}
