<?php

require_once __DIR__ . "/../BaseUnitTestCase.php";

/**
 * Test class for Util.
 * Generated by PHPUnit on 2011-12-13 at 08:30:23.
 */
class UtilUnitTest extends BaseUnitTestCase {


    /**
     * @todo Implement testArr_extract_key_pattern().
     */
    public function testArr_extract_key_pattern()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
